name: Crowdin Updater
description: An action that updates another repository based on modifications to the current one.
inputs:
  commit-message:
    description: Message that will be linked to the commit.
    default: Upload Translates
  locale-path:
    description: Directory where translations are.
    required: true
  upload-path:
    description: Directory where the translations will be copied.
    required: true
  target-repository:
    description: Github repository that new translations will be sent.
    required: true
  user-name:
    description: Name that will be linked to the commit.
    default: TranslateAction
  user-email:
    description: Email that will be linked to the commit.
    default: translate@action.github
branding:
  icon: 'archive'
  color: 'gray-dark'
runs:
  using: node12
  main: dist/index.js
